---
name: Linter
run-name: "Linter ${{ github.ref_name }} by @${{ github.actor }}"
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pre-commit
        run: pip install pre-commit
      - name: linting
        run: pre-commit run --all-files --show-diff-on-failure
